site_name: Grigora X
repo_name: Roo-FS/Grigora-X
repo_url: https://github.com/Roo-FS/Grigora-X

theme: 
  name: material
  logo: assets/ggx-icon.svg
  favicon: assets/ggx-icon.svg
  palette:
    primary: custom
  icon:
    repo: octicons/mark-github-16

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md